# Generated by Django 3.1.7 on 2022-06-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('contacts', models.CharField(max_length=255)),
                ('tattoo_description', models.TextField(blank=True, max_length=255, null=True)),
                ('sketch', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image_work', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('tatoo_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('client_name', models.CharField(max_length=124, verbose_name='Имя клиента')),
                ('client_review', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('image_status', models.CharField(choices=[('new', 'new'), ('old', 'old'), ('sketch', 'sketch')], default='new', max_length=8, verbose_name='status')),
            ],
        ),
    ]
