# Generated by Django 3.1.7 on 2022-06-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220619_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='name',
            field=models.CharField(default='Nati', max_length=120),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(default='Nati', max_length=124),
        ),
    ]
