# Generated by Django 3.1.7 on 2022-06-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220619_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Информация о мастере'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Страница мастера'},
        ),
    ]
