# Generated by Django 3.1.7 on 2022-06-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220619_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='tatoo_image',
            new_name='tattoo_image',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='tatoo_image',
            new_name='tattoo_image',
        ),
    ]
